### ISSUE TITLE
Can't make Instructions for development work

### ISSUE THREAD

**Issue by OrfeasLitos** [decrypto-org/blockchain-course#20]
It says [here](https://github.com/OrfeasLitos/blockchain-course#development) to run `cd api && yarn start`. When I do it, I get:
```
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module './assignments'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:611:15)
    at Function.Module._load (internal/modules/cjs/loader.js:537:25)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (blabla/blockchain-course/db/models/custom/assignment.js:3:21)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at mapJSFiles (blabla/blockchain-course/db/models/index.js:32:17)
    at Array.forEach (<anonymous>)
    at mapJSFiles (blabla/blockchain-course/db/helpers.js:15:6)
    at Object.<anonymous> (blabla/blockchain-course/db/models/index.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:736:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)
[nodemon] app crashed - waiting for file changes before starting...
```
Any ideas?

**Comment by cnasikas** [comment]
That is happening because there is no assignment inside the `assignment` folder.

Fixed by 8c6165d1fcfc6a9442e36676e833c73c995e6e42
