### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by OrfeasLitos** [decrypto-org/blockchain-course#22]
Upon clicking login, the page hangs and I get the following in the thing that's running in `api`:
```
UnhandledPromiseRejectionWarning: SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432
    at connection.connect.err (/blabla/repositories/blockchain-course/db/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:116:24)
    at Connection.connectingErrorHandler (/blabla/repositories/blockchain-course/db/node_modules/pg/lib/client.js:123:14)
    at Connection.emit (events.js:197:13)
    at Socket.reportStreamError (/blabla/repositories/blockchain-course/db/node_modules/pg/lib/connection.js:71:10)
    at Socket.emit (events.js:197:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by dionyziz** [comment]
Can you netcat -vvv to 127.0.0.1:5432?

**Comment by cnasikas** [comment]
That error indicates that you can connect to postgres. Are you sure that postgres is started and listens to port 5432 ?

**Comment by cnasikas** [comment]
Would you mind sharing your `DB_URI` env variable (without sensitive information)

**Comment by OrfeasLitos** [comment]
Most probably I forgot to open the DB, my bad. But the error should have been more helpful, see #23.
